# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_simulation <- function(max_gens, density, num_nests, males_per_winner) {
    invisible(.Call('contest_run_simulation', PACKAGE = 'contest', max_gens, density, num_nests, males_per_winner))
}

